//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIDZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мастер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мастер()
        {
            this.Ремонты_и_техобслуживания = new HashSet<Ремонты_и_техобслуживания>();
        }
    
        public System.Guid ID_мастера { get; set; }
        public string Квалификация { get; set; }
        public string Должность { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ремонты_и_техобслуживания> Ремонты_и_техобслуживания { get; set; }
    }
}
