//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIDZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public System.Guid ID_пользователя { get; set; }
        public string Логин { get; set; }
        public string PasswordHash { get; set; }
        public System.Guid Salt { get; set; }
        public int UserRole { get; set; }
    }
}
