//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIDZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ремонты_и_техобслуживания
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ремонты_и_техобслуживания()
        {
            this.Работы = new HashSet<Работа>();
        }
    
        public System.Guid ID_ремонта { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public Nullable<System.Guid> ID_мастера { get; set; }
        public System.Guid ID_оборудования { get; set; }
    
        public virtual Мастер Мастера { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа> Работы { get; set; }
    }
}
